---
- name: Install Kerberos
  yum: name={{ item }} state=present
  with_items:
    - krb5-workstation

- name: Configure Kerberos integration with AD
  template: 
    src: krb5.conf.j2 
    dest: /etc/krb5.conf
    owner: root 
    group: root 
    mode: 644
    backup: yes
